; Charger le loader de l’agent
extension=elastic_apm_loader.so
; Chemin vers la partie PHP de l’agent (installé par le .deb)
elastic_apm.bootstrap_php_part_file=/opt/elastic/apm-agent-php/src/bootstrap_php_part.php

; Config de base
elastic_apm.enabled = true
elastic_apm.service_name = myurgo-web
elastic_apm.environment = dev
elastic_apm.server_url = http://apm-server:8200

; (Optionnel) Verbosité des logs de l’agent
; elastic_apm.log_level = WARNING
elastic_apm.log_level = INFO